<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.8.0/dist/tf.min.js"></script>
</head>
<body>
  <h1>تصنيف سيارة</h1>
  <input type="file" id="inputImage" accept="image/*" />
  <div id="prediction"></div>

  <script>
    let model;
    // أولاً نحمّل النموذج
    tf.loadGraphModel('path/to/model.json').then(m => {
      model = m;
      console.log('Model loaded');
    });

    // عند اختيار صورة
    document.getElementById('inputImage').addEventListener('change', async e => {
      const img = document.createElement('img');
      img.src = URL.createObjectURL(e.target.files[0]);
      await img.decode();
      // نحول الصورة إلى tensor ونعدل حجمها
      let tensor = tf.browser.fromPixels(img)
        .resizeBilinear([224,224])  // تأكد من الحجم اللي دربت عليه
        .expandDims(0)
        .toFloat()
        .div(255);
      // نطلب التنبؤ
      const predictions = await model.predict(tensor).data();
      // نفترض عندك 4 كلاسات
      const classes = ['Sedan','SUV','Truck','Sport car'];
      const top = Array.from(predictions)
        .map((p,i) => ({class: classes[i], probability: p}))
        .sort((a,b) => b.probability - a.probability)[0];
      document.getElementById('prediction').innerText =
        `التصنيف: ${top.class} (ثقة ${(top.probability*100).toFixed(1)}%)`;
    });
  </script>
</body>
</html>
